export default {
    items : [
        {college_name: "",
         company_names: "",
         degree: ['Masters, Business Administration',
          'Bachelor, Technology, xstatusx July 2008'],
         designation: ['xxTitlexx'],
         email: 'xxxxxxx@xxx.com',
         experience: ['xxTitlexx',
          'xxCompanyNamexx',
          'April 2014 - Current',
          'xCityx, xStatex',
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio',
          'diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet.',
          '▪ Lorem ipsum dolor sit amet, consectetur.',
          '▪ Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio.',
          '▪ Nulla quis sem at nibh elementum imperdiet dolor sit.',
          'xxTitlexx',
          'xxCompanyNamexx',
          'October 2011 - March 2014',
          'xCityx, xStatex',
          '▪ Lorem ipsum dolor sit amet, consectetur.',
          '▪ Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio.',
          '▪ Lorem ipsum dolor sit amet, consectetuer adipiscing elit ean commodo ligula',
          'sectetuer adipiscing elit ean.',
          '▪ Lorem ipsum dolor sit amet, consectetur.',
          '▪ Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio.',
          'xxTitlexx',
          'xxCompanyNamexx',
          'October 2009 - October 2011',
          'xCityx, xStatex',
          'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo',
          'ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis',
          'parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies Lorem',
          'ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget',
          'dolor. Aenean massa.'],
         mobile_number: '0000000',
         name: 'conse siti',
         skills: ['Adobe',
          'Certification',
          'Servers',
          'Word',
          'Cms',
          'Excel',
          'Email',
          'Hardware',
          'Administration',
          'German',
          'Training',
          'Photoshop',
          'Engineering',
          'English',
          'Database'],
         total_experience: 4.42}
        ]
    }